language: c
matrix:
  include:
    - os: windows
      env: DESCR=windows-visualstudio
      language: shell
      script:
        - cd util
        - wget -O miktex-portable.exe https://miktex.org/download/ctan/systems/win32/miktex/setup/windows-x64/basic-miktex-2.9.7219-x64.exe
        - miktex-portable.exe --quiet --package-set=basic install
        - ./win/win32/vs2017/travisci.sh
    - os: windows
#     install: choco install mingw
      env: DESCR=windows-mingw
      script:
        - git clone --depth 1 https://github.com/wmcbrine/PDCurses.git ../pdcurses
        - export ADD_CURSES=Y
        - export PDCURSES_TOP=../../pdcurses
        - cd src
        - cp ../sys/winnt/Makefile.gcc ./Makefile
#        - gcc -E -CC -mms-bitfields -I../include -I../sys/winnt  -g -D"CURSES_GRAPHICS" -D"CURSES_BRIEF_INCLUDE" -DTILES -DMSWIN_GRAPHICS -DWIN32CON -D_WIN32_IE=0x0400 -D_WIN32_WINNT=0x0501 -DDLB -DSAFEPROCS  ../sys/winnt/windmain.c
#       
#        - mkdir o
#        - mingw32-make ../include/pm.h
#        - mingw32-make ../include/onames.h
#        - mingw32-make o/windmain.o
        - mingw32-make install

sudo: false
notifications:
  email: false
