language: c
matrix:
  include:
    - os: windows
      env: DESCR=windows-visualstudio
      language: shell
      script:
        - powershell --command systeminfo | Select-String "^OS Name","^OS Version"
#        - wsl -l -v
#        - powershell Invoke-WebRequest -Uri https://aka.ms/wsl-ubuntu-1604 -OutFile Ubuntu-1604.appx -UseBasicParsing -ErrorAction SilentlyContinue
#        - powershell Add-AppxPackage Ubuntu-1604.appx
#        - wget https://aka.ms/wsl-ubuntu-1604
#        - wsl ls -la
#        - ./win/win32/vs2017/travisci.sh
exclude:
    - os: windows
#     install: choco install mingw
      env: DESCR=windows-mingw
      script:
        - git clone --depth 1 https://github.com/wmcbrine/PDCurses.git ../pdcurses
        - export ADD_CURSES=Y
        - export PDCURSES_TOP=../../pdcurses
        - cd src
        - cp ../sys/winnt/Makefile.gcc ./Makefile
#       
#        - mkdir o
#        - mingw32-make ../include/pm.h
#        - mingw32-make ../include/onames.h
#        - mingw32-make o/windmain.o
        - mingw32-make install

sudo: false
notifications:
  email: false
