language: c
matrix:
  include:
    - os: windows
      env: DESCR=windows-visualstudio
      language: shell
      script:
        - ./win/win32/vs2017/travisci.sh
    - os: windows
#     install: choco install mingw
      env: DESCR=windows-mingw
      script:
        - git clone --depth 1 https://github.com/wmcbrine/PDCurses.git ../pdcurses
        - export ADD_CURSES=Y
        - export PDCURSES_TOP=../../pdcurses
        - cd src
        - cp ../sys/winnt/Makefile.gcc ./Makefile
        - mingw32-make install

sudo: false
notifications:
  email: false
